name: spelling

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v6
      - name: Spell Check Repo
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0
        with:
          config: ./.github/spell-check.toml
