name: spelling

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v6
      - name: Spell Check Repo
        uses: crate-ci/typos@06d010dfe4c84fdab1a25ea02b57b3585018ba80 # v1.42.3
        with:
          config: ./.github/spell-check.toml
